### ISSUE TITLE
Log event with multiply params

### ISSUE THREAD

**Issue by Insality** [defold/extension-firebase-analytics#1]
I want to pass multiply params in single event
Like *spend_currency* with fields, *type, amount, reason* etc.

For now we can pass event with only one param

**Comment by AGulev** [comment]
I am working on it.

**Comment by AGulev** [comment]
Solved https://github.com/defold/extension-firebase-analytics/commit/b89cf42f03f23f4a6bcfd04eb93002d7e14f23c3
