### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Dr-Klaus** [defold/extension-firebase-analytics#23]
Error when building with others plugins:

https://github.com/defold/extension-push/archive/master.zip
https://github.com/defold/extension-iap/archive/master.zip
https://github.com/AGulev/DefVideoAds/archive/master.zip
https://github.com/defold/extension-admob/archive/master.zip
https://github.com/defold/extension-firebase/archive/master.zip
https://github.com/defold/extension-firebase-analytics/archive/refs/tags/2.1.1.zip

Log:
[log.txt](https://github.com/defold/extension-firebase-analytics/files/9131944/log.txt)

**Comment by britzl** [comment]
```
duplicate symbol '_OBJC_CLASS_$_APMPlatformIdentitySupport' in:
    /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/job6498705526398958512/upload/firebase_analytics/lib/ios/GoogleAppMeasurement.framework/GoogleAppMeasurement(APMPlatformIdentitySupport.o)
    /var/folders/pf/p5g2vb2j0yx1x6vlmxdppc700000gn/T/job6498705526398958512/upload/extension-admob/lib/ios/GoogleAppMeasurementIdentitySupport.framework/GoogleAppMeasurementIdentitySupport(APMPlatformIdentitySupport.o)
```

**Comment by AGulev** [comment]
@britzl what version do we use
isn't it the fix? https://firebase.google.com/support/release-notes/ios#version_880_-_september_28_2021

**Comment by britzl** [comment]
Not sure, I'll set up a repro case and see if upgrading fixes it!

**Comment by britzl** [comment]
I have PRs prepared that will solve this issue. I've updated Firebase to C++ SDK version 8.10.0 and Firebase iOS SDK to version 8.13.0. The iOS SDK 8.13.0 version is matching the version used in extension-admob.

You can try this before the PR is merged using the following dependencies:

* https://github.com/defold/extension-firebase/archive/refs/heads/upgrade-8.10.0.zip
* https://github.com/defold/extension-firebase-analytics/archive/refs/heads/upgrade-8.10.0.zip

**Comment by Dr-Klaus** [comment]
> I have PRs prepared that will solve this issue. I've updated Firebase to C++ SDK version 8.10.0 and Firebase iOS SDK to version 8.13.0. The iOS SDK 8.13.0 version is matching the version used in extension-admob.
> 
> You can try this before the PR is merged using the following dependencies:
> 
> * https://github.com/defold/extension-firebase/archive/refs/heads/upgrade-8.10.0.zip
> * https://github.com/defold/extension-firebase-analytics/archive/refs/heads/upgrade-8.10.0.zip

I have checked upgrade-8.10.0.zip and there are not problems with it. All work as needed! Thanks!

**Comment by britzl** [comment]
> I have checked upgrade-8.10.0.zip and there are not problems with it. All work as needed! Thanks!

Thank you for confirming! I'll go ahead and merge then.
