### ISSUE TITLE
Update Firebase SDK to Version 10.22.0, to support iOS privacy manifest

### ISSUE THREAD

**Issue by vradyna-ms** [defold/extension-firebase-analytics#33]
Firebase has update SDK to support iOS privacy manifest. Please refer to the following link for more information: https://github.com/firebase/firebase-ios-sdk/releases/tag/10.22.0.

**Comment by AGulev** [comment]
Updated to the latest version
https://github.com/defold/extension-firebase-analytics/releases/tag/3.0.1

iOS privacy manifest part will be implemented with this issue https://github.com/defold/defold/issues/8378
