### ISSUE TITLE
fatal error: 'luautils.h' file not found

### ISSUE THREAD

**Issue by d954mas** [defold/extension-firebase-analytics#36]
Can't build app with defold 1.9.5

Sometimes androuid app not build. Sometimes build.

Something with extender and letter case

```
fatal error: 'luautils.h' file not found
```

May it be #include "LuaUtils.h"

**Comment by britzl** [comment]
> May it be #include "LuaUtils.h"

Where did you find this include?

**Comment by d954mas** [comment]
https://github.com/defold/extension-firebase-analytics/blob/dee2855493f7fa6640bb94686cdb118de8fa91c3/firebase_analytics/src/firebase_analytics.cpp#L10

On other extension sometimes you use #include "LuaUtils.h"
https://github.com/defold/extension-admob/blob/644bb7eb9166681633ff43942a3d4587cbd9ff3c/extension-admob/src/utils/LuaUtils.cpp#L1


Looks like in some cases build server run on case sensitive file system?

**Comment by d954mas** [comment]
I was wrong, i think this was something from lua.

So how it worked?
1)You have firebase native extension with "luautils.h" and "luautils.cpp"
https://github.com/defold/extension-firebase/blob/master/firebase/include/luautils.h
2)firebase analytics extension depends on firebase native extension. And use "luautils.h"
So "luautils.h" is correct path. But why it wasn't build for me is some cases:(

3)I test build android for few times and now i can't reproduce it.

May it be possible that native extension build in parallel and firebase analytics extension builded before firebase analytics

**Comment by d954mas** [comment]
I can't reproduced it so mb this issue can be closed. Mb it was something with build server when i created this issue

**Comment by britzl** [comment]
I'm not entirely sure what happened tbh. I'm closing this for now if it is working for you.
