### ISSUE TITLE
Example in documentation is not correct

### ISSUE THREAD

**Issue by d954mas** [defold/extension-firebase-analytics#37]
https://defold.com/extension-firebase-analytics/

firebase.analytics.log_string("character", "storm trooper")
firebase.analytics.log_int("kills", 152)
firebase.analytics.log_number("speed", 1.15)

https://defold.com/extension-firebase-analytics/firebase_api/#firebase.analytics.log_string:name-PARAMeter_name-PARAMeter_value

**Comment by AGulev** [comment]
could you pls make a PR with a fix?
