### ISSUE TITLE
[Bug][Android] Track events only in first session after install

### ISSUE THREAD

**Issue by Insality** [defold/extension-firebase-analytics#4]
For now, I see tracking events only after first launch (after installing)

If I start game in not first time, I can't see any events and basic tracking (ex. app launch)

On iOS all ok with this, only Android issue

**Comment by Insality** [comment]
Oh, I see different behaviour now
Sometimes i don't see event even after reinstalling game. Need to deep in this issue, will post more info later

**Comment by AGulev** [comment]
I've tested using `run.sh`. Everething works fine.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/2209596/58022272-691fe500-7b0d-11e9-9b3c-e70bc4ba08b9.png">
